SETTINGS = [
    'browser.bookmarks.autoExportHTML',  # true
    'browser.ctrlTab.sortByRecentlyUsed',  # true
    'browser.toolbars.bookmarks.visibility',  # newtab
    'browser.translations.automaticallyPopup',  # false
    'privacy.clearOnShutdown_v2.cookiesAndStorage',  # false
    'privacy.resistFingerprinting',  # false
]

with open('/home/hick/.librewolf/3vz18q2q.default-default/prefs.js', encoding='utf-8') as file:
    lines = file.readlines()
    with open('.librewolf/3vz18q2q.default-default/prefs.js', encoding='utf-8', mode='w') as save_file:
        save_file.write(
            """// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.\n\n"""
        )
        for line in lines:
            for setting in SETTINGS:
                if setting in line:
                    save_file.write(line)

